name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Test with unittest
      run: |
        coverage run -m unittest discover
        coverage report
        coverage xml

    - name: Publish to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        coveralls

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel